version: 2

jobs:
  32bit:
    docker:
      - image: quay.io/pypa/manylinux1_i686
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: /opt/python/cp36-cp36m/bin/pip install numpy scipy pytest-astropy pytest-xdist Cython jinja2
      - run:
          name: Run tests
          command: PYTHONHASHSEED=42 /opt/python/cp36-cp36m/bin/python setup.py test --parallel=4
  image-tests-mpl15:
    docker:
      - image: astrofrog/pytest-mpl-15:1.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy -a "--mpl"
  image-tests-mpl20:
    docker:
      - image: astrofrog/pytest-mpl-20:1.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy  -a "--mpl"
  image-tests-mpl21:
    docker:
      - image: astrofrog/pytest-mpl-21:1.0
    steps:
      - checkout
      - run:
          name: Run tests
          command: python3 setup.py test -P visualization --remote-data=astropy  -a "--mpl"


workflows:
  version: 2
  build_and_test:
    jobs:
      - 32bit
      - image-tests-mpl15
      - image-tests-mpl20
      - image-tests-mpl21
